// <auto-generated />
namespace SQRL.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LongUrlFormatStringAddedToCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LongUrlFormatStringAddedToCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201301062351469_LongUrlFormatStringAddedToCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
