// <auto-generated />
namespace SQRL.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LongUrlRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LongUrlRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201301062338589_LongUrlRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
