// <auto-generated />
namespace SQRL.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SetIdColumnCaseSensitive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetIdColumnCaseSensitive));
        
        string IMigrationMetadata.Id
        {
            get { return "201301061941247_SetIdColumnCaseSensitive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
